version: '3.8'

services:
  redis:
    container_name: ticket-redis
    image: redis:latest
    ports:
      - "7379:6379"

  mysql:
    container_name: ticket-mariadb
    image: mariadb:latest
    ports:
      - "4306:3306" #컨테이너 외부:내부
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      MARIADB_DATABASE: "${MARIADB_DATABASE}"
      MARIADB_ROOT_HOST: "${MARIADB_ROOT_HOST}"
      MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"