spring:
  application:
    name: gettoticket

  devtools:
    restart:
      enabled: true

  config:
    import: optional:classpath:application-db.yml

  thymeleaf:
    enabled: true
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: true

server:
  shutdown: graceful

logging: classpath:logback-spring.xml